#在Spring Boot应用程序中，server.port 属性是用来设置应用内嵌服务器（比如Tomcat、Jetty等）绑定并监听HTTP请求的端口。
#当配置为 8088 时，意味着该Spring Boot应用启动后，其HTTP服务将在本地主机上通过8088端口对外提供服务。因此，用户可以通过URL如 http://localhost:8088 来访问该应用。
server:
  port: 8088

spring:
  #这一部分配置的是Spring Boot应用的数据源（DataSource）相关属性，这里使用的是Druid数据源。
  datasource:
    druid:
      #这一行指定了连接MySQL数据库时使用的JDBC驱动类名。
      driver-class-name: com.mysql.cj.jdbc.Driver
      #这一行是数据库连接URL，它包含了连接MySQL数据库所需的所有信息
      url: jdbc:mysql://localhost:3306/knowledgebase?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      url: jdbc:mysql://134.107.67.26:3306/knowledgebase?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root

##      生产和生产环境
      password: 123456
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/




  servlet:
    multipart:
      enabled: true # 启用多部分解析器（默认通常是启用的）
      max-file-size: 512MB # 单个文件最大上传大小
      max-request-size: 512MB # 整个请求的最大大小（包括所有上传文件）
  config:
    activate:
      on-profile:

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    #比如表名address_book映射到类AddressBook，字段user_name映射到属性userName
    map-underscore-to-camel-case: true
    # 设置日志实现类为 StdOutImpl，这样MyBatis执行SQL时的日志会输出到控制台（stdout），方便开发调试。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#用来指定上传文件的存储目录
upload:
  video:
#    开发环境路径
    path: E:\\upload\\video\\

#    生产环境路径
#     path: /upload/video/


  image:
    path: E:\\upload\\image\\
    #     path: /upload/image/

  attachment:
    path: E:\\upload\\attachment\\
    #     path: /upload/attachment/








